[versions]
activity-compose = "1.11.0"
activity-ktx = "1.11.0"
androidx-junit = "1.3.0"
android-gradle-plugin = "8.12.3"
appcompat = "1.7.1"
blessed = "0.61"
clikt = "5.0.3"
compose = "1.9.1"
compose-webview-multiplatform = "2.0.3"
composecompiler = "1.5.8"
composeandroid = "1.9.4"
composebom = "2023.03.00"
core-ktx = "1.17.0"
coroutines = "1.10.2"
espresso-core = "3.7.0"
fragment-ktx = "1.8.9"
jnr = "2.2.18"
junit = "4.13.2"
kcef = "2024.04.20.4"
kermit = "2.0.8"
kotlin = "2.2.21"
lifecycle-runtime-ktx = "2.9.4"
qrcode-kotlin = "3.3.0"
serialization = "1.9.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "composeandroid" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
blessed = { module = "com.github.weliem.blessed-bluez:blessed", version.ref = "blessed"}
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
compose = { module = "androidx.compose.ui:ui", version.ref = "composeandroid" }
compose-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "composeandroid" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeandroid" }
compose-webview-multiplatform = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "compose-webview-multiplatform" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
jnr = { module = "com.github.jnr:jnr-ffi", version.ref = "jnr" }
junit = { module = "junit:junit", version.ref = "junit" }
kcef = { group = "dev.datlag", name = "kcef", version.ref = "kcef" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
qrcode-kotlin = { module = "io.github.g0dkar:qrcode-kotlin", version.ref = "qrcode-kotlin" }
serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serialization"}
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeandroid" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeandroid" }

[bundles]
compose = ["compose", "compose-graphics", "compose-preview"]

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidGradlePlugin = { id = "com.android.application", version.ref = "android-gradle-plugin" }
